/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AlbumAlbumIdRouteImport } from './routes/album/$albumId'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as SlideshowAlbumIdRouteImport } from './routes/slideshow/$albumId'
import { Route as AdminAlbumsAlbumIdRouteImport } from './routes/admin/albums/$albumId'
import { Route as AdminAlbumsCreateRouteImport } from './routes/admin/albums/create'
import { Route as AdminPhotosIndexRouteImport } from './routes/admin/photos/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlideshowAlbumIdRoute = SlideshowAlbumIdRouteImport.update({
  id: '/slideshow/$albumId',
  path: '/slideshow/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsAlbumIdRoute = AdminAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAlbumsCreateRoute = AdminAlbumsCreateRouteImport.update({
  id: '/albums/create',
  path: '/albums/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPhotosIndexRoute = AdminPhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/slideshow/$albumId': typeof SlideshowAlbumIdRoute
  '/admin/': typeof AdminIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/admin/albums/$albumId': typeof AdminAlbumsAlbumIdRoute
  '/admin/albums/create': typeof AdminAlbumsCreateRoute
  '/admin/photos/': typeof AdminPhotosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/slideshow/$albumId': typeof SlideshowAlbumIdRoute
  '/admin': typeof AdminIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/admin/albums/$albumId': typeof AdminAlbumsAlbumIdRoute
  '/admin/albums/create': typeof AdminAlbumsCreateRoute
  '/admin/photos': typeof AdminPhotosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/slideshow/$albumId': typeof SlideshowAlbumIdRoute
  '/admin/': typeof AdminIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/admin/albums/$albumId': typeof AdminAlbumsAlbumIdRoute
  '/admin/albums/create': typeof AdminAlbumsCreateRoute
  '/admin/photos/': typeof AdminPhotosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/album/$albumId'
    | '/slideshow/$albumId'
    | '/admin/'
    | '/photos/'
    | '/admin/albums/$albumId'
    | '/admin/albums/create'
    | '/admin/photos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/album/$albumId'
    | '/slideshow/$albumId'
    | '/admin'
    | '/photos'
    | '/admin/albums/$albumId'
    | '/admin/albums/create'
    | '/admin/photos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/album/$albumId'
    | '/slideshow/$albumId'
    | '/admin/'
    | '/photos/'
    | '/admin/albums/$albumId'
    | '/admin/albums/create'
    | '/admin/photos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  SlideshowAlbumIdRoute: typeof SlideshowAlbumIdRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slideshow/$albumId': {
      id: '/slideshow/$albumId'
      path: '/slideshow/$albumId'
      fullPath: '/slideshow/$albumId'
      preLoaderRoute: typeof SlideshowAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums/$albumId': {
      id: '/admin/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/admin/albums/$albumId'
      preLoaderRoute: typeof AdminAlbumsAlbumIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/albums/create': {
      id: '/admin/albums/create'
      path: '/albums/create'
      fullPath: '/admin/albums/create'
      preLoaderRoute: typeof AdminAlbumsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/photos/': {
      id: '/admin/photos/'
      path: '/photos'
      fullPath: '/admin/photos/'
      preLoaderRoute: typeof AdminPhotosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlbumsAlbumIdRoute: typeof AdminAlbumsAlbumIdRoute
  AdminAlbumsCreateRoute: typeof AdminAlbumsCreateRoute
  AdminPhotosIndexRoute: typeof AdminPhotosIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAlbumsAlbumIdRoute: AdminAlbumsAlbumIdRoute,
  AdminAlbumsCreateRoute: AdminAlbumsCreateRoute,
  AdminPhotosIndexRoute: AdminPhotosIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  SlideshowAlbumIdRoute: SlideshowAlbumIdRoute,
  PhotosIndexRoute: PhotosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
